# Generated by Django 5.0.2 on 2025-03-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_file_url_remove_post_image_url_post_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='model_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='used_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
