# Generated by Django 5.0.2 on 2025-03-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('not_requested', '신청 전'), ('pending', '승인 대기 중'), ('approved', '승인됨'), ('rejected', '거부됨')], default='not_requested', max_length=20),
        ),
    ]
